server:
  port: 5050
 
spring:
  application:
    name: payment-client

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defultZone: http://localhost:8761/eureka
      
      
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"